### ISSUE TITLE
Application Crash on DCF File Parsing

### ISSUE THREAD

**Issue by dmitri-mcguckin** [oresat/CANopen-monitor#59]
More information to follow.

```
Traceback (most recent call last):
File "/home/monitor/.local/bin//canopen-monitor", line 8, in <module>
sys.exit(main())
File "/home/monitor/.local/lib/python3.9/site-packages/canopen_monitor/__main__.py", line 68, in main
eds_configs = load_eds_files()
File "/home/monitor/.local/lib/python3.9/site-packages/canopen_monitor/__main__.py", line 19, in load_eds_files
config = load_eds_file(full_path)
File "/home/monitor/.local/lib/python3.9/site-packages/canopen_monitor/parse/eds.py", line 190, in load_eds_file
return EDS(list(map(lambda x: x.strip(), file.read().split('\n'))))
File "/home/monitor/.local/lib/python3.9/site-packages/canopen_monitor/parse/eds.py", line 149, in __init__
id = section[0][1:-1].split('sub')
IndexError: list index out of range
```

**Comment by dmitri-mcguckin** [comment]
Sample DCF file.

[battery.dcf.txt](https://github.com/oresat/CANopen-monitor/files/6417500/battery.dcf.txt)

**Comment by Boneill3** [comment]
The issue is caused by a blank line as the last line of the DCF file

**Comment by Boneill3** [comment]
It looks like ending with a subindex actually requires a single blank line and ending with a non subindex requires no blank line.
